// variants/inertia_vue/app/frontend/pages/Privacy.vue
<script setup lang="ts">
import { usePage, Head } from '@inertiajs/vue3';
import Layout from '@/layouts/Layout.vue';

const page = usePage();
const appName = page.props.app_name as string;
</script>

<template>
  <Layout>
    <Head title="Privacy Policy" />
    <div class="flex min-h-screen items-center justify-center py-12">
      <div class="max-w-4xl px-6">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-5xl mb-8">
          Privacy Policy
        </h1>
        <div class="prose prose-gray dark:prose-invert max-w-none">
          <p class="text-lg leading-8 text-gray-600 dark:text-gray-300">
            At {{ appName }}, we take your privacy seriously. This policy describes how we collect,
            use, and protect your personal information.
          </p>
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">1. Information We Collect</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            We collect information you provide directly to us, such as when you create an account.
          </p>
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">2. How We Use Your Information</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            We use your information to provide, maintain, and improve our services.
          </p>
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">3. Information Sharing</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            We do not share your personal information with third parties except as described in this policy.
          </p>
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">4. Data Security</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            We implement appropriate security measures to protect your information.
          </p>
        </div>
        <div class="mt-10">
          <a
            href="/"
            class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500"
          >
            Back to Home
          </a>
        </div>
      </div>
    </div>
  </Layout>
</template>

// variants/inertia_svelte/app/frontend/pages/Privacy.svelte
<script lang="ts">
  import { page } from '@inertiajs/svelte';
  import Layout from '@/layouts/Layout.svelte';
</script>

<svelte:head>
  <title>Privacy Policy - {page.props.app_name}</title>
</svelte:head>

<Layout>
  <div class="flex min-h-screen items-center justify-center py-12">
    <div class="max-w-4xl px-6">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-5xl mb-8">
        Privacy Policy
      </h1>
      <div class="prose prose-gray dark:prose-invert max-w-none">
        <p class="text-lg leading-8 text-gray-600 dark:text-gray-300">
          At {page.props.app_name}, we take your privacy seriously. This policy describes how we collect,
          use, and protect your personal information.
        </p>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">1. Information We Collect</h2>
        <p class="text-gray-600 dark:text-gray-300 mb-6">
          We collect information you provide directly to us, such as when you create an account.
        </p>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">2. How We Use Your Information</h2>
        <p class="text-gray-600 dark:text-gray-300 mb-6">
          We use your information to provide, maintain, and improve our services.
        </p>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">3. Information Sharing</h2>
        <p class="text-gray-600 dark:text-gray-300 mb-6">
          We do not share your personal information with third parties except as described in this policy.
        </p>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">4. Data Security</h2>
        <p class="text-gray-600 dark:text-gray-300 mb-6">
          We implement appropriate security measures to protect your information.
        </p>
      </div>
      <div class="mt-10">
        <a
          href="/"
          class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500"
        >
          Back to Home
        </a>
      </div>
    </div>
  </div>
</Layout>
